src/dvc_task/proc/manager.py, tests/proc/conftest.py, tests/proc/test_manager.py
- adds `ProcessManager.follow` to follow child process redirected output (`tail -f`)
=> proc: implement redirected out follow

setup.cfg, tests/worker/test_temporary.py
Mark celery worker monitoring tests as flaky for now (see https://github.com/iterative/dvc-task/issues/6)
=> tests: mark worker monitor tests flaky on macos

.cruft.json, .github/workflows/release.yml, .github/workflows/tests.yml, pyproject.toml, setup.cfg
See https://github.com/iterative/py-template/pull/17. There is a merge conflict, so `update-template` is not able to create a PR on itself.
=> cruft updates: force nox color, single workflow run and setuptools_scm for versioning

.github/workflows/tests.yml
Windows tests timed out: https://github.com/iterative/dvc-task/runs/6548550094?check_suite_focus=true.
=> ci: bump tests timeout to 15 minutes

src/dvc_task/proc/manager.py
- Adjust API to make it more obvious that `ProcessManager.run` was not intended run a process, it returns a celery task signature which needs to be scheduled.
- Also allows the user to specify whether or not the generated signature is immutable (useful when using celery chaining)
=> proc: clarify that ProcessManager.run returns a task signature

src/dvc_task/proc/process.py
Sets pgrp in spawned proc so signals are not forwarded from the original parent. Signal handlers are still inherited (so caller is responsible for configuring SIG_IGN/SIG_DFL/custom handlers as desired)
Fixes https://github.com/iterative/dvc-task/issues/60
=> proc: set pgrp in spawned daemon processes

src/dvc_task/proc/manager.py, src/dvc_task/proc/process.py
fix: #53
Currently, the dump and load process info file at a time may cause some
error. Write to a temp file and then rename it eases this problem. But a
final solution would still be required in someday later.
=> Better handle for process info dump

src/dvc_task/app/filesystem.py, tests/app/test_filesystem.py
fix: #68
We currently lack a way to clean processed messages which makes our
queue status list longer and longer. This PR add a new method `purge` to
solve this problem.
1. Add a new method `purge` to remove processed messages like `queued`
ones.
2. Unify the `iter_queued` method and `iter_processed` method.
3. Unify the `purge` and `reject` method.
4. Add a new test for `purge`
=> FSApp: add a new method purge

setup.cfg, src/dvc_task/app/filesystem.py
- unpins kombu alpha requirement and moves version check to runtime in FSApp to unblock conda release
Once 5.3.0 (final/non-alpha) is released on pypi it can be repinned
related: https://github.com/iterative/dvc-task/issues/72
=> release: temporarily unpin kombu to unblock conda release

.cruft.json, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/tests.yml, CONTRIBUTING.rst, noxfile.py, setup.cfg
=> cruft: update template

src/dvc_task/worker/temporary.py
fix: #77
This bug is because in our heartbeat detecting the `inspect.schedule` and
`inspect.reserved` didn't return current tasks in queue.  The
`inspect.reserved` it will lists tasks that had been prefetched, but we
had disabled this prefetch behavior. It is always empty for now. And the
prematurely shutdown is caused when the it meets the time gap between
two tasks. Here I directly go into the queue directory and return all
of the tasks in the queue to solve this problem.
=> worker: monitor shuts down worker prematurely

src/dvc_task/proc/manager.py, src/dvc_task/proc/process.py
fix: #93
Our old solution on #53, can reduce possibility of race condition, but it still happens occasionally.
1. Add locks to write and read operations to prevent this kind of error.
2. Use reraise to simplify the code in `__getitem__`
=> Add locks to process operations to prevent race conditions.

src/dvc_task/proc/manager.py, tests/proc/test_manager.py
Need a flag to know if the kill operation success.
1. Raise `ProcessLookupError` if `os.kill` didn't kill the process.
1. Reraise `KeyError` to ProcessLookupError if the task isn't founded.
related to https://github.com/iterative/dvc/pull/8580
=> Raise proper exception in `send_signal` if we haven't kill the desired process.

src/dvc_task/proc/manager.py, tests/proc/test_manager.py
fix: #100
Required from dvc to stop the checkpoint during running.
1. Add a new method interrupt to send SIGINT to tasks
2. Modify the unit test for this new method.
=> Add a new method interrupt to send SIGINT to tasks

src/dvc_task/proc/manager.py, tests/proc/test_manager.py
When using killpg, we need to call with group id instead of pid.
related to #100
1. Get group id by pid for `killpg`
2. Modify `kill` and `terminate` 's default groups to `False` for better compatibility.
=> Automatically get group id by pid, and change some default value

src/dvc_task/proc/process.py
Trying to fix https://github.com/iterative/dvc/issues/8570#issue-1450769780.
=> ProcessInfo: save atomically

src/dvc_task/proc/process.py
See https://github.com/iterative/dvc-task/pull/104#discussion_r1066962471.
=> process: remove lock/unlock

src/dvc_task/app/filesystem.py, tests/app/test_filesystem.py
related: iterative/dvc#8676, iterative/dvc#8787
=> fsapp: add clean() method

src/dvc_task/app/filesystem.py, src/dvc_task/worker/temporary.py, tests/worker/test_temporary.py
When workers exit they will end up leaving filesystem broker control messages that never expire and will never be ack'd in the future, we should just purge them on `clean`
=> fsapp: remove pidbox replies on clean

noxfile.py, pyproject.toml
It's a test dependency, so it's safe to ignore.
Revert when https://github.com/celery/pytest-celery/pull/305 gets merged.
=> safety: ignore py vulnerabiility

pyproject.toml, tests/conftest.py
=> tests: drop pytest-celery from tests dependencies
